INSERT INTO courses (course_id, code, name) VALUES (1, '12.01', 'Quimica I');
INSERT INTO courses (course_id, code, name) VALUES (2, '31.08', 'Sistemas de Representacion');
INSERT INTO courses (course_id, code, name) VALUES (3, '93.17', 'Matematica I');
INSERT INTO courses (course_id, code, name) VALUES (4, '93.18', 'Algebra Lineal');
INSERT INTO courses (course_id, code, name) VALUES (5, '94.21', 'Formacion General I');
INSERT INTO courses (course_id, code, name) VALUES (6, '12.02', 'Quimica II');
INSERT INTO courses (course_id, code, name) VALUES (7, '71.55', 'Informatica General');
INSERT INTO courses (course_id, code, name) VALUES (8, '93.02', 'Matematica II');
INSERT INTO courses (course_id, code, name) VALUES (9, '93.41', 'Fisica I');
INSERT INTO courses (course_id, code, name) VALUES (10, '94.24', 'Metodologia del Aprendizaje');
INSERT INTO courses (course_id, code, name) VALUES (11, '16.01', 'Biología Molecular y Celular');
INSERT INTO courses (course_id, code, name) VALUES (12, '71.44', 'Estructura de Datos y Programación');
INSERT INTO courses (course_id, code, name) VALUES (13, '93.03', 'Matematica III');
INSERT INTO courses (course_id, code, name) VALUES (14, '93.42', 'Fisica II');
INSERT INTO courses (course_id, code, name) VALUES (15, '16.02', 'Histología y Anatomía');
INSERT INTO courses (course_id, code, name) VALUES (16, '93.24', 'Probabil.y Estadistica(k/s)');
INSERT INTO courses (course_id, code, name) VALUES (17, '93.43', 'Fisica III');
INSERT INTO courses (course_id, code, name) VALUES (18, '93.65', 'Matemática IV');
INSERT INTO courses (course_id, code, name) VALUES (19, '16.03', 'Fisiología');
INSERT INTO courses (course_id, code, name) VALUES (20, '16.12', 'Biomateriales');
INSERT INTO courses (course_id, code, name) VALUES (21, '21.06', 'Electrotecnia');
INSERT INTO courses (course_id, code, name) VALUES (22, '93.44', 'Fisica IV');
INSERT INTO courses (course_id, code, name) VALUES (23, '93.57', 'Matematica V ( K )');
INSERT INTO courses (course_id, code, name) VALUES (24, '16.06', 'Señales y Sistemas');
INSERT INTO courses (course_id, code, name) VALUES (25, '16.10', 'Electrónica Analógica y Digital');
INSERT INTO courses (course_id, code, name) VALUES (26, '16.13', 'Biomecánica');
INSERT INTO courses (course_id, code, name) VALUES (27, '16.14', 'Fisiología Cuantitativa');
INSERT INTO courses (course_id, code, name) VALUES (28, '93.54', 'Metodos Numericos ( K )');
INSERT INTO courses (course_id, code, name) VALUES (29, '16.11', 'Sistemas de Control');
INSERT INTO courses (course_id, code, name) VALUES (30, '16.15', 'Procesamiento de Señales Biomédicas');
INSERT INTO courses (course_id, code, name) VALUES (31, '16.17', 'Instrumentación Biomédica I');
INSERT INTO courses (course_id, code, name) VALUES (32, '16.20', 'Biomedicina Estructural y Computacional');
INSERT INTO courses (course_id, code, name) VALUES (33, '61.31', 'Derecho para Ingenieros');
INSERT INTO courses (course_id, code, name) VALUES (34, '11.15', 'Organizacion Industrial');
INSERT INTO courses (course_id, code, name) VALUES (35, '16.16', 'Procesamiento de Imágenes Biomédicas');
INSERT INTO courses (course_id, code, name) VALUES (36, '16.18', 'Instrumentación Biomédica II');
INSERT INTO courses (course_id, code, name) VALUES (37, '16.19', 'Biosensores');
INSERT INTO courses (course_id, code, name) VALUES (38, '16.21', 'Bioinformática');
INSERT INTO courses (course_id, code, name) VALUES (39, '16.22', 'Informática Médica');
INSERT INTO courses (course_id, code, name) VALUES (40, '16.23', 'Órganos Artificiales');
INSERT INTO courses (course_id, code, name) VALUES (41, '16.24', 'Ingeniería de Rehabilitación');
INSERT INTO courses (course_id, code, name) VALUES (42, '16.30', 'Proyecto Final de Carrera (Anual)');
INSERT INTO courses (course_id, code, name) VALUES (43, '94.28', 'Formacion General II');
INSERT INTO courses (course_id, code, name) VALUES (44, '12.83', 'Seguridad Ocupacional y Ambiental');
INSERT INTO courses (course_id, code, name) VALUES (45, '16.33', 'Ingeniería Hospitalaria');
INSERT INTO courses (course_id, code, name) VALUES (46, '61.23', 'Economia para Ingenieros');
INSERT INTO courses (course_id, code, name) VALUES (47, '11.76', 'Gestión de la Calidad');
INSERT INTO courses (course_id, code, name) VALUES (48, '16.26', 'Neurociencias');
INSERT INTO courses (course_id, code, name) VALUES (49, '16.27', 'Ingeniería de Tejidos');
INSERT INTO courses (course_id, code, name) VALUES (50, '16.28', 'Computación de Alto Desempeño y Distribuida');
INSERT INTO courses (course_id, code, name) VALUES (51, '16.29', 'Diseño de Fármacos');
INSERT INTO courses (course_id, code, name) VALUES (52, '16.31', 'Normativa Biomédica y Marco Regulatorio');
INSERT INTO courses (course_id, code, name) VALUES (53, '16.32', 'Redes Neuronales en bioingeniería');
INSERT INTO courses (course_id, code, name) VALUES (54, '94.29', 'Formacion para Emprendedores');
INSERT INTO courses (course_id, code, name) VALUES (55, '21.32', 'Tecnologia de Mat. Electricos');
INSERT INTO courses (course_id, code, name) VALUES (56, '21.45', 'Eficiencia Energética');
INSERT INTO courses (course_id, code, name) VALUES (57, '21.65', 'Instalaciones Electricas y Luminotecnia');
INSERT INTO courses (course_id, code, name) VALUES (58, '21.71', 'Electrotecnia I');
INSERT INTO courses (course_id, code, name) VALUES (59, '21.72', 'Mantenimiento de Máquinas e Instalaciones Eléctricas');
INSERT INTO courses (course_id, code, name) VALUES (60, '21.73', 'Energias Alternativas');
INSERT INTO courses (course_id, code, name) VALUES (61, '21.74', 'Instrumentos y Mediciones Eléctricas');
INSERT INTO courses (course_id, code, name) VALUES (62, '21.79', 'Electrotecnia II');
INSERT INTO courses (course_id, code, name) VALUES (63, '21.80', 'Maquinas Electricas I');
INSERT INTO courses (course_id, code, name) VALUES (64, '21.81', 'Maquinas Electricas II');
INSERT INTO courses (course_id, code, name) VALUES (65, '21.82', 'Centrales Electricas');
INSERT INTO courses (course_id, code, name) VALUES (66, '21.83', 'Transmision de la Energia Electrica');
INSERT INTO courses (course_id, code, name) VALUES (67, '21.84', 'Proyecto Final');
INSERT INTO courses (course_id, code, name) VALUES (68, '21.85', 'Sistemas Electricos de Potencia');
INSERT INTO courses (course_id, code, name) VALUES (69, '21.86', 'Diseño de Lineas de Transmision y Estaciones Transformadoras');
INSERT INTO courses (course_id, code, name) VALUES (70, '21.87', 'Mercado Electrico');
INSERT INTO courses (course_id, code, name) VALUES (71, '21.88', 'Distribucion de la Energia Electrica');
INSERT INTO courses (course_id, code, name) VALUES (72, '22.06', 'Introduccion a la Computacion');
INSERT INTO courses (course_id, code, name) VALUES (73, '22.07', 'Programacion I');
INSERT INTO courses (course_id, code, name) VALUES (74, '22.08', 'Algoritmos y Estructura de Datos');
INSERT INTO courses (course_id, code, name) VALUES (75, '22.20', 'Electronica General');
INSERT INTO courses (course_id, code, name) VALUES (76, '22.28', 'Electronica de Potencia');
INSERT INTO courses (course_id, code, name) VALUES (77, '22.37', 'Fundamentos de Electromagnetismo');
INSERT INTO courses (course_id, code, name) VALUES (78, '22.42', 'Laboratorio de Electronica');
INSERT INTO courses (course_id, code, name) VALUES (79, '22.58', 'Instrumentación y control');
INSERT INTO courses (course_id, code, name) VALUES (80, '31.19', 'Estatica y Resistencia de Materiales');
INSERT INTO courses (course_id, code, name) VALUES (81, '31.21', 'Termodinamica');
INSERT INTO courses (course_id, code, name) VALUES (82, '31.24', 'Mecanica de Fluidos');
INSERT INTO courses (course_id, code, name) VALUES (83, '31.27', 'Mecanismos y Elementos de Maquinas');
INSERT INTO courses (course_id, code, name) VALUES (84, '31.38', 'Turbomaquinas');
INSERT INTO courses (course_id, code, name) VALUES (85, '93.07', 'Metodos Numericos');
INSERT INTO courses (course_id, code, name) VALUES (86, '94.23', 'Formacion General III');
INSERT INTO courses (course_id, code, name) VALUES (87, '95.01', 'Practica Laboral');
INSERT INTO courses (course_id, code, name) VALUES (88, '11.36', 'Innovaciòn y Competitividad');
INSERT INTO courses (course_id, code, name) VALUES (89, '11.91', 'Metodologia de Investigacion');
INSERT INTO courses (course_id, code, name) VALUES (90, '14.03', 'Gestion de la Innovacion');
INSERT INTO courses (course_id, code, name) VALUES (91, '14.23', 'Diagnostico del Riesgo Operativo');
INSERT INTO courses (course_id, code, name) VALUES (92, '14.33', 'Identificación de Distribución de Probabilidad');
INSERT INTO courses (course_id, code, name) VALUES (93, '14.34', 'Modelos Avanzados de Regresión');
INSERT INTO courses (course_id, code, name) VALUES (94, '14.35', 'Modelos Scoring');
INSERT INTO courses (course_id, code, name) VALUES (95, '14.37', 'Analisis de Encuestas');
INSERT INTO courses (course_id, code, name) VALUES (96, '14.38', 'Estructura Tributaria Argentina');
INSERT INTO courses (course_id, code, name) VALUES (97, '14.40', 'Ingeniería y Cambio Climatico');
INSERT INTO courses (course_id, code, name) VALUES (98, '16.34', 'Electromedicina');
INSERT INTO courses (course_id, code, name) VALUES (99, '16.35', 'Dispositivos Bioelectronicos');
INSERT INTO courses (course_id, code, name) VALUES (100, '16.37', 'Biologia para Ingenieros');
INSERT INTO courses (course_id, code, name) VALUES (101, '16.39', 'Interfaces Bioelectrónicas');
INSERT INTO courses (course_id, code, name) VALUES (102, '16.42', 'Fisiología Cuantitativa');
INSERT INTO courses (course_id, code, name) VALUES (103, '22.01', 'Teoria de Circuitos');
INSERT INTO courses (course_id, code, name) VALUES (104, '22.02', 'Electrotecnia I');
INSERT INTO courses (course_id, code, name) VALUES (105, '22.05', 'Anal.de Señales y Sist.digit.');
INSERT INTO courses (course_id, code, name) VALUES (106, '22.12', 'Electronica II');
INSERT INTO courses (course_id, code, name) VALUES (107, '22.13', 'Electronica III');
INSERT INTO courses (course_id, code, name) VALUES (108, '22.14', 'Electronica IV');
INSERT INTO courses (course_id, code, name) VALUES (109, '22.15', 'Electronica V');
INSERT INTO courses (course_id, code, name) VALUES (110, '22.21', 'Electromagnetismo');
INSERT INTO courses (course_id, code, name) VALUES (111, '22.22', 'Antenas y Radiopropagacion');
INSERT INTO courses (course_id, code, name) VALUES (112, '22.29', 'Microondas');
INSERT INTO courses (course_id, code, name) VALUES (113, '22.31', 'Diseño de Equipos Electronicos');
INSERT INTO courses (course_id, code, name) VALUES (114, '22.33', 'Microelectronica');
INSERT INTO courses (course_id, code, name) VALUES (115, '22.45', 'Redes Neuronales');
INSERT INTO courses (course_id, code, name) VALUES (116, '22.46', 'Procesamiento Adaptativo de Señales');
INSERT INTO courses (course_id, code, name) VALUES (117, '22.47', 'Procesamiento de Voz');
INSERT INTO courses (course_id, code, name) VALUES (118, '22.48', 'Procesamiento de Imagenes');
INSERT INTO courses (course_id, code, name) VALUES (119, '22.49', 'Laboratorio de Dsp_fpga');
INSERT INTO courses (course_id, code, name) VALUES (120, '22.53', 'Tecnología de materiales electrónicos');
INSERT INTO courses (course_id, code, name) VALUES (121, '22.59', 'Electrónica I');
INSERT INTO courses (course_id, code, name) VALUES (122, '22.61', 'Transmision de la Informacion');
INSERT INTO courses (course_id, code, name) VALUES (123, '22.64', 'Comunicaciones Digitales');
INSERT INTO courses (course_id, code, name) VALUES (124, '22.66', 'Redes Digitales');
INSERT INTO courses (course_id, code, name) VALUES (125, '22.67', 'Señales Aleatorias');
INSERT INTO courses (course_id, code, name) VALUES (126, '22.85', 'Sistemas de Control');
INSERT INTO courses (course_id, code, name) VALUES (127, '22.88', 'Sensores y Actuadores');
INSERT INTO courses (course_id, code, name) VALUES (128, '22.90', 'Automacion Industrial');
INSERT INTO courses (course_id, code, name) VALUES (129, '22.92', 'Fundamentos de la Teoría de Control');
INSERT INTO courses (course_id, code, name) VALUES (130, '22.93', 'Control Automatico');
INSERT INTO courses (course_id, code, name) VALUES (131, '22.95', 'Matería de Focalización con autorización de la Sra. Directora del Departamento');
INSERT INTO courses (course_id, code, name) VALUES (132, '22.99', 'Lab. de Microprocesadores');
INSERT INTO courses (course_id, code, name) VALUES (133, '31.81', 'Tecnologia de Maquinas');
INSERT INTO courses (course_id, code, name) VALUES (134, '31.99', 'Mecatronica Aplicada');
INSERT INTO courses (course_id, code, name) VALUES (135, '41.02', 'Geologia para Ingenieros');
INSERT INTO courses (course_id, code, name) VALUES (136, '61.32', 'Derecho para Ingenieros');
INSERT INTO courses (course_id, code, name) VALUES (137, '61.82', 'Macroeconomia');
INSERT INTO courses (course_id, code, name) VALUES (138, '93.16', 'Matematica Discreta');
INSERT INTO courses (course_id, code, name) VALUES (139, '93.47', 'Fisica IV (Electronicos)');
INSERT INTO courses (course_id, code, name) VALUES (140, '94.42', 'Comunicacion Estrategica');
INSERT INTO courses (course_id, code, name) VALUES (141, '94.52', 'Ingles II (Ingeniero)');
INSERT INTO courses (course_id, code, name) VALUES (142, '10.01', 'Proyecto Final de Ingeniería Industrial (Anual)');
INSERT INTO courses (course_id, code, name) VALUES (143, '10.02', 'Gestión Ambiental');
INSERT INTO courses (course_id, code, name) VALUES (144, '10.03', 'Gestión de Proyectos (i)');
INSERT INTO courses (course_id, code, name) VALUES (145, '10.04', 'Plantas Industriales');
INSERT INTO courses (course_id, code, name) VALUES (146, '10.05', 'Redes de Valor e Innovación de Modelos de Negocios');
INSERT INTO courses (course_id, code, name) VALUES (147, '10.07', 'Creatividad');
INSERT INTO courses (course_id, code, name) VALUES (148, '11.02', 'Org. de la Produccion II');
INSERT INTO courses (course_id, code, name) VALUES (149, '11.09', 'Calidad II');
INSERT INTO courses (course_id, code, name) VALUES (150, '11.10', 'Organizacion de la Produccion I');
INSERT INTO courses (course_id, code, name) VALUES (151, '11.14', 'Diseño de Producto');
INSERT INTO courses (course_id, code, name) VALUES (152, '11.16', 'Materiales y Procesos');
INSERT INTO courses (course_id, code, name) VALUES (153, '11.18', 'Ingenieria y Mantenimiento');
INSERT INTO courses (course_id, code, name) VALUES (154, '11.19', 'Costos Industriales');
INSERT INTO courses (course_id, code, name) VALUES (155, '11.20', 'Presupuesto y Control');
INSERT INTO courses (course_id, code, name) VALUES (156, '11.34', 'Taller de Modelizacion de Productos');
INSERT INTO courses (course_id, code, name) VALUES (157, '11.37', 'Diseño de Experimentos');
INSERT INTO courses (course_id, code, name) VALUES (158, '11.39', 'Marketing');
INSERT INTO courses (course_id, code, name) VALUES (159, '11.40', 'Marketing II');
INSERT INTO courses (course_id, code, name) VALUES (160, '11.46', 'Planeamiento Estrategico');
INSERT INTO courses (course_id, code, name) VALUES (161, '11.59', 'Logistica');
INSERT INTO courses (course_id, code, name) VALUES (162, '11.63', 'Simulacion');
INSERT INTO courses (course_id, code, name) VALUES (163, '11.71', 'Dinamica de Sistemas II');
INSERT INTO courses (course_id, code, name) VALUES (164, '11.73', 'Teoria de la Decision');
INSERT INTO courses (course_id, code, name) VALUES (165, '11.75', 'Tecnologías y Procesos de Producción');
INSERT INTO courses (course_id, code, name) VALUES (166, '11.77', 'Estadística Aplicada I');
INSERT INTO courses (course_id, code, name) VALUES (167, '11.78', 'Estadística Aplicada II');
INSERT INTO courses (course_id, code, name) VALUES (168, '11.79', 'Sistemas y Modelos');
INSERT INTO courses (course_id, code, name) VALUES (169, '11.86', 'Investigación de Operaciones I');
INSERT INTO courses (course_id, code, name) VALUES (170, '11.87', 'Investigación de Operaciones II');
INSERT INTO courses (course_id, code, name) VALUES (171, '11.89', 'Formulación y Evaluación de Proyectos');
INSERT INTO courses (course_id, code, name) VALUES (172, '12.46', 'Introduccion Al Proceso de Fabricacion de Aceros');
INSERT INTO courses (course_id, code, name) VALUES (173, '12.47', 'Control de Procesos/Laboratorio de Control de Procesos');
INSERT INTO courses (course_id, code, name) VALUES (174, '12.84', 'Introduccion a la Ingenieria Ambiental');
INSERT INTO courses (course_id, code, name) VALUES (175, '14.01', 'Envases y Embalajes');
INSERT INTO courses (course_id, code, name) VALUES (176, '14.02', 'Diseño y Gestion de un Centro de Distribucion');
INSERT INTO courses (course_id, code, name) VALUES (177, '14.04', 'Diseño y Desarrollo Asistido por Computadora');
INSERT INTO courses (course_id, code, name) VALUES (178, '14.05', 'Creatividad');
INSERT INTO courses (course_id, code, name) VALUES (179, '14.06', 'Proyecto y Diseño de una Planta Industrial');
INSERT INTO courses (course_id, code, name) VALUES (180, '14.07', 'Ingenieria del Proceso de Ventas');
INSERT INTO courses (course_id, code, name) VALUES (181, '14.08', 'Diseño y Gestion de Marcas');
INSERT INTO courses (course_id, code, name) VALUES (182, '14.09', 'Evolucion y Tendencia de la Innovacion');
INSERT INTO courses (course_id, code, name) VALUES (183, '14.10', 'Adopción y Uso de Innovaciones');
INSERT INTO courses (course_id, code, name) VALUES (184, '14.11', 'Responsabilidad Social Empresaria');
INSERT INTO courses (course_id, code, name) VALUES (185, '14.12', 'Reingenieria de Procesos');
INSERT INTO courses (course_id, code, name) VALUES (186, '14.13', 'Diseño Grafico de Envases');
INSERT INTO courses (course_id, code, name) VALUES (187, '14.14', 'Introduccion a la Consultoria');
INSERT INTO courses (course_id, code, name) VALUES (188, '14.15', 'Finanzas para Emprendedores');
INSERT INTO courses (course_id, code, name) VALUES (189, '14.16', 'Ingenieros para el Desarrollo');
INSERT INTO courses (course_id, code, name) VALUES (190, '14.17', 'Economia y Marketing de Mercados en Red');
INSERT INTO courses (course_id, code, name) VALUES (191, '14.18', 'Gestion Portuaria');
INSERT INTO courses (course_id, code, name) VALUES (192, '14.19', 'Actualización Tecnológica sobre Competitividad');
INSERT INTO courses (course_id, code, name) VALUES (193, '14.20', 'Gestion del Conocimiento');
INSERT INTO courses (course_id, code, name) VALUES (194, '14.21', 'Negocios de Diseño');
INSERT INTO courses (course_id, code, name) VALUES (195, '14.22', 'Analisis Estrategico de Costos de Manufactura');
INSERT INTO courses (course_id, code, name) VALUES (196, '14.24', 'Seleccion de Materiales');
INSERT INTO courses (course_id, code, name) VALUES (197, '14.25', 'Taller Siderurgico');
INSERT INTO courses (course_id, code, name) VALUES (198, '14.26', 'Introduccion a la Complejidad de los Negocios');
INSERT INTO courses (course_id, code, name) VALUES (199, '14.27', 'Mecanizado Asistido por Computadora');
INSERT INTO courses (course_id, code, name) VALUES (200, '14.28', 'Agronegocios');
INSERT INTO courses (course_id, code, name) VALUES (201, '14.29', 'Sustentabilidad, una Cuestión de Diseño');
INSERT INTO courses (course_id, code, name) VALUES (202, '14.30', 'Cultura y Cambio Organizacional');
INSERT INTO courses (course_id, code, name) VALUES (203, '14.31', 'Neuromanagement');
INSERT INTO courses (course_id, code, name) VALUES (204, '14.32', 'Scor-supply Chain Operations Reference');
INSERT INTO courses (course_id, code, name) VALUES (205, '14.36', 'Segmentacion de Clientes');
INSERT INTO courses (course_id, code, name) VALUES (206, '14.39', 'Gestión de TIC');
INSERT INTO courses (course_id, code, name) VALUES (207, '14.41', 'Redes de Valor y Modelos de Negocios');
INSERT INTO courses (course_id, code, name) VALUES (208, '14.42', 'Desarrollo Inmobiliario');
INSERT INTO courses (course_id, code, name) VALUES (209, '14.43', 'Optimización lineal y convexa');
INSERT INTO courses (course_id, code, name) VALUES (210, '14.44', 'Derecho Laboral y Seguridad Social en la Empresa');
INSERT INTO courses (course_id, code, name) VALUES (211, '14.45', 'Marketing On Line');
INSERT INTO courses (course_id, code, name) VALUES (212, '14.46', 'Lean Manufacturing');
INSERT INTO courses (course_id, code, name) VALUES (213, '14.47', 'Energías Renovables');
INSERT INTO courses (course_id, code, name) VALUES (214, '14.48', 'Empresa y desarrollo sustentable');
INSERT INTO courses (course_id, code, name) VALUES (215, '14.49', 'Integración de Procesos y Sistemas en SCM');
INSERT INTO courses (course_id, code, name) VALUES (216, '14.50', 'Análisis de Riesgos y Puntos Críticos de Control');
INSERT INTO courses (course_id, code, name) VALUES (217, '14.51', 'Business Analytics');
INSERT INTO courses (course_id, code, name) VALUES (218, '14.52', 'Eficiencia Energética');
INSERT INTO courses (course_id, code, name) VALUES (219, '14.53', 'Eficiencia Energética');
INSERT INTO courses (course_id, code, name) VALUES (220, '14.54', 'Strategy Development');
INSERT INTO courses (course_id, code, name) VALUES (221, '14.55', 'Marketing de Servicios');
INSERT INTO courses (course_id, code, name) VALUES (222, '14.56', 'Ciudades Inteligentes');
INSERT INTO courses (course_id, code, name) VALUES (223, '14.57', 'Visión Comercial del Ingeniero Industrial');
INSERT INTO courses (course_id, code, name) VALUES (224, '14.58', 'Estrategias de Marketing');
INSERT INTO courses (course_id, code, name) VALUES (225, '14.59', 'Lean Six sigma White Belt');
INSERT INTO courses (course_id, code, name) VALUES (226, '14.60', 'Creatividad e Innovacion en el Marketing');
INSERT INTO courses (course_id, code, name) VALUES (227, '14.61', 'Introduccion a Estrategia');
INSERT INTO courses (course_id, code, name) VALUES (228, '14.62', 'Negocios en la era de internet');
INSERT INTO courses (course_id, code, name) VALUES (229, '14.63', 'Knowledge Management and Big Data in Business');
INSERT INTO courses (course_id, code, name) VALUES (230, '14.64', 'TPm1x Creative Problem Solving and Decision Making');
INSERT INTO courses (course_id, code, name) VALUES (231, '14.65', 'CircularX Circular Economy: An Introduction');
INSERT INTO courses (course_id, code, name) VALUES (232, '14.66', 'Math 226.3x Nonlinear differential equations: Order and Chaos');
INSERT INTO courses (course_id, code, name) VALUES (233, '14.67', 'bem1105x Pricing Options with Mathematical Models');
INSERT INTO courses (course_id, code, name) VALUES (234, '14.68', 'vf201x Valoración de Futbolistas con el Método AHP');
INSERT INTO courses (course_id, code, name) VALUES (235, '14.69', 'steel101x Introduction to Steel');
INSERT INTO courses (course_id, code, name) VALUES (236, '14.70', 'yca2015-1-2x Understanding the Federal Reserve');
INSERT INTO courses (course_id, code, name) VALUES (237, '14.71', 'Policy Analysis Using Interrupted Time Series');
INSERT INTO courses (course_id, code, name) VALUES (238, '14.72', 'Analytics');
INSERT INTO courses (course_id, code, name) VALUES (239, '14.73', 'Diseño de innovaciones');
INSERT INTO courses (course_id, code, name) VALUES (240, '21.09', 'Máquinas Eléctricas');
INSERT INTO courses (course_id, code, name) VALUES (241, '21.10', 'Instalaciones Eléctricas');
INSERT INTO courses (course_id, code, name) VALUES (242, '22.10', 'Electronica e Instrumentacion');
INSERT INTO courses (course_id, code, name) VALUES (243, '30.01', 'Mecánica y Mecanismos');
INSERT INTO courses (course_id, code, name) VALUES (244, '30.02', 'Máquinas Térmicas');
INSERT INTO courses (course_id, code, name) VALUES (245, '30.03', 'Instalaciones Térmicas');
INSERT INTO courses (course_id, code, name) VALUES (246, '31.22', 'Mecanica de Fluidos');
INSERT INTO courses (course_id, code, name) VALUES (247, '31.25', 'Termodinamica');
INSERT INTO courses (course_id, code, name) VALUES (248, '31.65', 'Procesos de Manufactura II');
INSERT INTO courses (course_id, code, name) VALUES (249, '31.67', 'Procesos de Manufactura I');
INSERT INTO courses (course_id, code, name) VALUES (250, '31.83', 'Proyecto de Materiales');
INSERT INTO courses (course_id, code, name) VALUES (251, '31.90', 'Integridad Estructural');
INSERT INTO courses (course_id, code, name) VALUES (252, '31.94', 'Tecnologia de Materiales Compuestos');
INSERT INTO courses (course_id, code, name) VALUES (253, '31.95', 'Fisica y Mecanica de Aceros');
INSERT INTO courses (course_id, code, name) VALUES (254, '31.96', 'Deformacion y Fractura de Materiales');
INSERT INTO courses (course_id, code, name) VALUES (255, '31.97', 'Corrosion y Degradacion de Materiales');
INSERT INTO courses (course_id, code, name) VALUES (256, '31.98', 'Laboratorio Avanzado de Materiales');
INSERT INTO courses (course_id, code, name) VALUES (257, '61.10', 'Economia Internacional');
INSERT INTO courses (course_id, code, name) VALUES (258, '61.28', 'Economia');
INSERT INTO courses (course_id, code, name) VALUES (259, '61.50', 'Finanzas de la Empresa');
INSERT INTO courses (course_id, code, name) VALUES (260, '71.56', 'Programacion Basica');
INSERT INTO courses (course_id, code, name) VALUES (261, '81.03', 'Sistemas de Información');
INSERT INTO courses (course_id, code, name) VALUES (262, '81.21', 'Gestion de Ventas');
INSERT INTO courses (course_id, code, name) VALUES (263, '93.36', 'Probabilidad');
INSERT INTO courses (course_id, code, name) VALUES (264, '93.51', 'Mecanica General');
INSERT INTO courses (course_id, code, name) VALUES (265, '94.27', 'Administración Recursos Humanos');
INSERT INTO courses (course_id, code, name) VALUES (266, '94.62', 'Etica en los Negocios');
INSERT INTO courses (course_id, code, name) VALUES (267, '12.09', 'Quimica');
INSERT INTO courses (course_id, code, name) VALUES (268, '16.50', 'Introducción a la Bioinformática');
INSERT INTO courses (course_id, code, name) VALUES (269, '22.09', 'Fundamentos Electronicos de la Informatica');
INSERT INTO courses (course_id, code, name) VALUES (270, '22.27', 'Transmision de Datos');
INSERT INTO courses (course_id, code, name) VALUES (271, '61.24', 'Economia para Ingenieros');
INSERT INTO courses (course_id, code, name) VALUES (272, '72.02', 'Organizacion Basica de la Computadora');
INSERT INTO courses (course_id, code, name) VALUES (273, '72.03', 'Introduccion a la Informatica');
INSERT INTO courses (course_id, code, name) VALUES (274, '72.07', 'Protocolos de Comunicacion');
INSERT INTO courses (course_id, code, name) VALUES (275, '72.08', 'Arquitecturas de Computadoras');
INSERT INTO courses (course_id, code, name) VALUES (276, '72.11', 'Sistemas Operativos');
INSERT INTO courses (course_id, code, name) VALUES (277, '72.18', 'Programacion Funcional');
INSERT INTO courses (course_id, code, name) VALUES (278, '72.20', 'Redes de Informacion');
INSERT INTO courses (course_id, code, name) VALUES (279, '72.22', 'Sistemas Tolerantes a Fallas');
INSERT INTO courses (course_id, code, name) VALUES (280, '72.23', 'Diseño y Construccion de Compiladores');
INSERT INTO courses (course_id, code, name) VALUES (281, '72.25', 'Simulacion de Sistemas');
INSERT INTO courses (course_id, code, name) VALUES (282, '72.27', 'Sistemas de Inteligencia Artificial');
INSERT INTO courses (course_id, code, name) VALUES (283, '72.28', 'Topologia de Internet: Analisis y Modelado');
INSERT INTO courses (course_id, code, name) VALUES (284, '72.29', 'Tipos para Lenguajes de Programación');
INSERT INTO courses (course_id, code, name) VALUES (285, '72.31', 'Programacion Imperativa');
INSERT INTO courses (course_id, code, name) VALUES (286, '72.32', 'Diseño y Procesamiento de Doc Xml');
INSERT INTO courses (course_id, code, name) VALUES (287, '72.33', 'Programacion Orientada a Objetos');
INSERT INTO courses (course_id, code, name) VALUES (288, '72.34', 'Estructura de Datos y Algoritmos');
INSERT INTO courses (course_id, code, name) VALUES (289, '72.35', 'Ingenieria de Software I');
INSERT INTO courses (course_id, code, name) VALUES (290, '72.36', 'Interaccion Hombre-computadora (HCI)');
INSERT INTO courses (course_id, code, name) VALUES (291, '72.37', 'Base de Datos I');
INSERT INTO courses (course_id, code, name) VALUES (292, '72.38', 'Proyecto de Aplicaciones Web');
INSERT INTO courses (course_id, code, name) VALUES (293, '72.39', 'Automatas, Teoria de Lenguajes y Compiladores');
INSERT INTO courses (course_id, code, name) VALUES (294, '72.40', 'Ingenieria de Software II');
INSERT INTO courses (course_id, code, name) VALUES (295, '72.41', 'Base de Datos II');
INSERT INTO courses (course_id, code, name) VALUES (296, '72.42', 'Programacion de Objetos Distribuidos');
INSERT INTO courses (course_id, code, name) VALUES (297, '72.43', 'Gestión de Proyectos Informáticos');
INSERT INTO courses (course_id, code, name) VALUES (298, '72.44', 'Criptografia y Seguridad');
INSERT INTO courses (course_id, code, name) VALUES (299, '72.45', 'Proyecto Final');
INSERT INTO courses (course_id, code, name) VALUES (300, '72.46', 'Robotica Basada en Comportamiento');
INSERT INTO courses (course_id, code, name) VALUES (301, '72.49', 'Sistemas Tolerantes a Fallas');
INSERT INTO courses (course_id, code, name) VALUES (302, '72.50', 'Introducción Al Desarrollo de Videojuegos');
INSERT INTO courses (course_id, code, name) VALUES (303, '72.51', 'Tecnologias para Web 2.0 y Redes Sociales');
INSERT INTO courses (course_id, code, name) VALUES (304, '72.52', 'Análisis y Tratamiento de Imágenes');
INSERT INTO courses (course_id, code, name) VALUES (305, '72.53', 'Visión Computacional 3D');
INSERT INTO courses (course_id, code, name) VALUES (306, '72.54', 'Olap y Extraccion de Informacion');
INSERT INTO courses (course_id, code, name) VALUES (307, '72.55', 'Ontologias en la Web');
INSERT INTO courses (course_id, code, name) VALUES (308, '72.56', 'Automatizacion e Integracion de Sistemas de Informacion');
INSERT INTO courses (course_id, code, name) VALUES (309, '72.57', 'Sistemas Embebidos');
INSERT INTO courses (course_id, code, name) VALUES (310, '72.58', 'Computacion Grafica');
INSERT INTO courses (course_id, code, name) VALUES (311, '72.59', 'Sistemas de Inteligencia Artificial II');
INSERT INTO courses (course_id, code, name) VALUES (312, '72.60', 'Programacion Funcional');
INSERT INTO courses (course_id, code, name) VALUES (313, '72.61', 'Taller de Diseño de Videojuegos');
INSERT INTO courses (course_id, code, name) VALUES (314, '72.64', 'Cloud Computing');
INSERT INTO courses (course_id, code, name) VALUES (315, '72.65', 'Desarrollo de Videojuegos 2D en iPhone OS');
INSERT INTO courses (course_id, code, name) VALUES (316, '72.66', 'Sistemas Embebidos');
INSERT INTO courses (course_id, code, name) VALUES (317, '72.67', 'Robotica Cinematica Computacional');
INSERT INTO courses (course_id, code, name) VALUES (318, '72.68', 'Arte y Ciencia Interactivos');
INSERT INTO courses (course_id, code, name) VALUES (319, '72.69', 'Seguridad de Software basada en Flujo de Información');
INSERT INTO courses (course_id, code, name) VALUES (320, '72.70', 'Modelos e Imágenes Fractales');
INSERT INTO courses (course_id, code, name) VALUES (321, '72.71', 'Integración de Sistemas de Información');
INSERT INTO courses (course_id, code, name) VALUES (322, '72.72', 'Analisis y Verificación de Modelos y Códigos');
INSERT INTO courses (course_id, code, name) VALUES (323, '72.73', 'Aprendizaje por Refuerzo en Robótica');
INSERT INTO courses (course_id, code, name) VALUES (324, '72.74', 'VIsualizacion de Informacion');
INSERT INTO courses (course_id, code, name) VALUES (325, '72.75', 'Aprendizaje Automático (Machine Learning)');
INSERT INTO courses (course_id, code, name) VALUES (326, '72.77', 'Técnicas Automáticas para Testing de Software');
INSERT INTO courses (course_id, code, name) VALUES (327, '72.78', 'OLAP Espacial');
INSERT INTO courses (course_id, code, name) VALUES (328, '72.79', 'Sistemas Multiagente I');
INSERT INTO courses (course_id, code, name) VALUES (329, '72.80', 'Big Data');
INSERT INTO courses (course_id, code, name) VALUES (330, '72.81', 'Simulación y Animación de Sistemas Multipartículas');
INSERT INTO courses (course_id, code, name) VALUES (331, '72.82', 'Tópicos de NOSQL');
INSERT INTO courses (course_id, code, name) VALUES (332, '72.83', 'Técnicas avanzadas de HCI con uso de rastreadores de ojos y manos');
INSERT INTO courses (course_id, code, name) VALUES (333, '72.84', 'Base de Datos Espaciales y Sistemas de Información Geográfica');
INSERT INTO courses (course_id, code, name) VALUES (334, '72.85', 'Análisis de Datos en la Web Semántica');
INSERT INTO courses (course_id, code, name) VALUES (335, '72.86', 'Técnicas Avanzadas en Videojuegos');
INSERT INTO courses (course_id, code, name) VALUES (336, '72.87', 'Diseño Sonoro para Animación y Videojuegos');
INSERT INTO courses (course_id, code, name) VALUES (337, '93.26', 'Analisis Matematico I');
INSERT INTO courses (course_id, code, name) VALUES (338, '93.28', 'Analisis Matematico II');
INSERT INTO courses (course_id, code, name) VALUES (339, '93.35', 'Logica Computacional');
INSERT INTO courses (course_id, code, name) VALUES (340, '93.58', 'Algebra');
INSERT INTO courses (course_id, code, name) VALUES (341, '93.59', 'Matematica Discreta');
INSERT INTO courses (course_id, code, name) VALUES (342, '93.75', 'Metodos Numericos Avanzados');
INSERT INTO courses (course_id, code, name) VALUES (343, '94.26', 'Comunicacion Organizacional');
INSERT INTO courses (course_id, code, name) VALUES (344, '11.83', 'Gestion de Operaciones');
INSERT INTO courses (course_id, code, name) VALUES (345, '11.84', 'Gestion de Proyectos');
INSERT INTO courses (course_id, code, name) VALUES (346, '11.85', 'Toma de Decisiones');
INSERT INTO courses (course_id, code, name) VALUES (347, '61.12', 'Gestion Financiera');
INSERT INTO courses (course_id, code, name) VALUES (348, '61.40', 'Economia y Finanzas Internacionales');
INSERT INTO courses (course_id, code, name) VALUES (349, '61.81', 'Microeconomía');
INSERT INTO courses (course_id, code, name) VALUES (350, '61.90', 'Derecho Publico y Privado');
INSERT INTO courses (course_id, code, name) VALUES (351, '61.92', 'Derecho Aduanero');
INSERT INTO courses (course_id, code, name) VALUES (352, '71.80', 'Utilitarios en Informatica');
INSERT INTO courses (course_id, code, name) VALUES (353, '71.85', 'Programacion');
INSERT INTO courses (course_id, code, name) VALUES (354, '71.88', 'Gestion de Datos');
INSERT INTO courses (course_id, code, name) VALUES (355, '81.02', 'Introduccion a la Licenciatura en Adm y Sistemas');
INSERT INTO courses (course_id, code, name) VALUES (356, '81.07', 'Sistemas Contables');
INSERT INTO courses (course_id, code, name) VALUES (357, '81.08', 'Aplicacion de las Telecomunicaciones');
INSERT INTO courses (course_id, code, name) VALUES (358, '81.11', 'Contabilidad Gerencial');
INSERT INTO courses (course_id, code, name) VALUES (359, '81.20', 'Comercializacion');
INSERT INTO courses (course_id, code, name) VALUES (360, '81.23', 'Comercio Electronico');
INSERT INTO courses (course_id, code, name) VALUES (361, '81.25', 'Impuestos');
INSERT INTO courses (course_id, code, name) VALUES (362, '81.26', 'Comercio Exterior');
INSERT INTO courses (course_id, code, name) VALUES (363, '81.30', 'Analisis y Modelado de Procesos de Negocios');
INSERT INTO courses (course_id, code, name) VALUES (364, '81.31', 'Analisis y Diseño de Aplicaciones Informaticas');
INSERT INTO courses (course_id, code, name) VALUES (365, '81.36', 'Sistemas Integrados de Gestion Empresaria II');
INSERT INTO courses (course_id, code, name) VALUES (366, '81.38', 'Integracion de Procesos de Negocios y Aplic Inf');
INSERT INTO courses (course_id, code, name) VALUES (367, '81.39', 'Sistemas Integrados de Gestion Empresaria I');
INSERT INTO courses (course_id, code, name) VALUES (368, '81.41', 'Estrategia Empresaria');
INSERT INTO courses (course_id, code, name) VALUES (369, '81.45', 'Seminario de Actualizacion');
INSERT INTO courses (course_id, code, name) VALUES (370, '81.46', 'Auditoria General y de Sistemas');
INSERT INTO courses (course_id, code, name) VALUES (371, '81.52', 'Negocios y Tecnologia en Internet');
INSERT INTO courses (course_id, code, name) VALUES (372, '81.55', 'Diagnostico Empresario y Plan de Accion ( Trabajo Final )');
INSERT INTO courses (course_id, code, name) VALUES (373, '81.56', 'Arquitectura de la Tecnologia Informática');
INSERT INTO courses (course_id, code, name) VALUES (374, '81.60', 'Sistemas Integrados de Gestion en la Ind de Serv');
INSERT INTO courses (course_id, code, name) VALUES (375, '81.61', 'Modelado Avanzado de Proc e Intelig de Neg');
INSERT INTO courses (course_id, code, name) VALUES (376, '81.63', 'Marketing Internacional');
INSERT INTO courses (course_id, code, name) VALUES (377, '81.64', 'Gestión y Sistemas de Información de la Logistica Internacional');
INSERT INTO courses (course_id, code, name) VALUES (378, '93.20', 'Analisis Matematico');
INSERT INTO courses (course_id, code, name) VALUES (379, '93.21', 'Algebra');
INSERT INTO courses (course_id, code, name) VALUES (380, '93.39', 'Estadistica');
INSERT INTO courses (course_id, code, name) VALUES (381, '94.10', 'Formacion para Emprendedores');
INSERT INTO courses (course_id, code, name) VALUES (382, '94.40', 'Estructura de las Organizaciones');
INSERT INTO courses (course_id, code, name) VALUES (383, '94.41', 'Gestion de los Recursos Humanos');
INSERT INTO courses (course_id, code, name) VALUES (384, '94.60', 'Panorama Historico Global');
INSERT INTO courses (course_id, code, name) VALUES (385, '94.61', 'Filosofia');
INSERT INTO courses (course_id, code, name) VALUES (386, '94.63', 'Epistemologia y Heuristica');
INSERT INTO courses (course_id, code, name) VALUES (387, '94.90', 'Inglés I (analista)');
INSERT INTO courses (course_id, code, name) VALUES (388, '11.35', 'Gestion de Proyectos Tecnologicos');
INSERT INTO courses (course_id, code, name) VALUES (389, '12.28', 'Residuos sólidos y residuos peligrosos');
INSERT INTO courses (course_id, code, name) VALUES (390, '12.87', 'Tratamiento de Efluentes');
INSERT INTO courses (course_id, code, name) VALUES (391, '21.08', 'Electrotecnia');
INSERT INTO courses (course_id, code, name) VALUES (392, '21.41', 'Instalaciones Electricas');
INSERT INTO courses (course_id, code, name) VALUES (393, '22.54', 'Electronica Industrial');
INSERT INTO courses (course_id, code, name) VALUES (394, '22.56', 'Sensores y Actuadores');
INSERT INTO courses (course_id, code, name) VALUES (395, '22.57', 'Microprocesadores y Control');
INSERT INTO courses (course_id, code, name) VALUES (396, '22.73', 'Instrumentacion y Control Industrial');
INSERT INTO courses (course_id, code, name) VALUES (397, '22.94', 'Control Discreto');
INSERT INTO courses (course_id, code, name) VALUES (398, '30.05', 'Manufactura');
INSERT INTO courses (course_id, code, name) VALUES (399, '30.06', 'Motores de Combustión Interna I A');
INSERT INTO courses (course_id, code, name) VALUES (400, '30.07', 'Elementos Finitos I');
INSERT INTO courses (course_id, code, name) VALUES (401, '30.08', 'Procesos de Manufactura I');
INSERT INTO courses (course_id, code, name) VALUES (402, '30.09', 'Motores de Combustión Interna I B');
INSERT INTO courses (course_id, code, name) VALUES (403, '30.10', 'Fractomecánica');
INSERT INTO courses (course_id, code, name) VALUES (404, '30.11', 'Ensayos No Destructivos');
INSERT INTO courses (course_id, code, name) VALUES (405, '30.12', 'Diseño Mecánico II');
INSERT INTO courses (course_id, code, name) VALUES (406, '30.13', 'Motores de Combustión Interna II');
INSERT INTO courses (course_id, code, name) VALUES (407, '30.14', 'Mecánica de Fluidos Computacional');
INSERT INTO courses (course_id, code, name) VALUES (408, '30.15', 'Energías Renovables');
INSERT INTO courses (course_id, code, name) VALUES (409, '31.04', 'Elementos de Maquinas');
INSERT INTO courses (course_id, code, name) VALUES (410, '31.16', 'Ensayo de Materiales');
INSERT INTO courses (course_id, code, name) VALUES (411, '31.20', 'Diseño Mecanico');
INSERT INTO courses (course_id, code, name) VALUES (412, '31.26', 'Mecanica de Fluidos');
INSERT INTO courses (course_id, code, name) VALUES (413, '31.30', 'Materiales Polimericos');
INSERT INTO courses (course_id, code, name) VALUES (414, '31.33', 'Mecanismos');
INSERT INTO courses (course_id, code, name) VALUES (415, '31.34', 'Estatica');
INSERT INTO courses (course_id, code, name) VALUES (416, '31.35', 'Resistencia de Materiales');
INSERT INTO courses (course_id, code, name) VALUES (417, '31.36', 'Metalurgia Fisica I');
INSERT INTO courses (course_id, code, name) VALUES (418, '31.37', 'Transferencia de Calor');
INSERT INTO courses (course_id, code, name) VALUES (419, '31.40', 'Proyecto Mecánico');
INSERT INTO courses (course_id, code, name) VALUES (420, '31.58', 'Proyectos Mecatronicos');
INSERT INTO courses (course_id, code, name) VALUES (421, '31.66', 'Hidráulica, Neumática y Plc');
INSERT INTO courses (course_id, code, name) VALUES (422, '31.68', 'Instalaciones Industriales');
INSERT INTO courses (course_id, code, name) VALUES (423, '31.73', 'Aire Acondicionado y Refrigeración');
INSERT INTO courses (course_id, code, name) VALUES (424, '31.82', 'Sistemas Mecatronicos');
INSERT INTO courses (course_id, code, name) VALUES (425, '31.84', 'Estructuras Automotrices');
INSERT INTO courses (course_id, code, name) VALUES (426, '31.85', 'Transmisiones Automotrices');
INSERT INTO courses (course_id, code, name) VALUES (427, '31.86', 'Sistemas Mecatronicos del Automovil');
INSERT INTO courses (course_id, code, name) VALUES (428, '31.88', 'Proyecto Automotor');
INSERT INTO courses (course_id, code, name) VALUES (429, '31.89', 'Dinamica del Automovil');
INSERT INTO courses (course_id, code, name) VALUES (430, '31.92', 'Elementos Finitos II');
INSERT INTO courses (course_id, code, name) VALUES (431, '32.54', 'Construccion Naval');
INSERT INTO courses (course_id, code, name) VALUES (432, '32.55', 'Estructura de Buques I');
INSERT INTO courses (course_id, code, name) VALUES (433, '32.56', 'Alistamiento Naval');
INSERT INTO courses (course_id, code, name) VALUES (434, '32.66', 'Hidrostática y Estabilidad');
INSERT INTO courses (course_id, code, name) VALUES (435, '32.67', 'Resistencia y Propulsión');
INSERT INTO courses (course_id, code, name) VALUES (436, '71.57', 'Introduccion a la Programacion');
INSERT INTO courses (course_id, code, name) VALUES (437, '93.22', 'Prob.y Estadistica(i/m/q)');
INSERT INTO courses (course_id, code, name) VALUES (438, '93.38', 'Matematica V');
INSERT INTO courses (course_id, code, name) VALUES (439, '93.66', 'Métodos Numéricos (M)');
INSERT INTO courses (course_id, code, name) VALUES (440, '32.52', 'Maquinas Marinas I');
INSERT INTO courses (course_id, code, name) VALUES (441, '32.53', 'Maquinas Marinas II');
INSERT INTO courses (course_id, code, name) VALUES (442, '32.57', 'Proyecto de Buques');
INSERT INTO courses (course_id, code, name) VALUES (443, '32.64', 'Plantas Propulsoras Marinas');
INSERT INTO courses (course_id, code, name) VALUES (444, '32.68', 'Astilleros y Mantenimiento de Buques');
INSERT INTO courses (course_id, code, name) VALUES (445, '32.70', 'Embarque');
INSERT INTO courses (course_id, code, name) VALUES (446, '32.80', 'Practica Laboral');
INSERT INTO courses (course_id, code, name) VALUES (447, '11.58', 'Dinamica de Sistemas');
INSERT INTO courses (course_id, code, name) VALUES (448, '11.68', 'Estadistica Superior');
INSERT INTO courses (course_id, code, name) VALUES (449, '12.30', 'Industrializacion y Economia Petrolera');
INSERT INTO courses (course_id, code, name) VALUES (450, '12.34', 'Quimica Organica para Petroleo');
INSERT INTO courses (course_id, code, name) VALUES (451, '21.07', 'Maquinas e Instalaciones Electricas');
INSERT INTO courses (course_id, code, name) VALUES (452, '31.45', 'Materiales Industriales II');
INSERT INTO courses (course_id, code, name) VALUES (453, '41.03', 'Perforacion Petrolera I');
INSERT INTO courses (course_id, code, name) VALUES (454, '41.04', 'Perforacion Petrolera II');
INSERT INTO courses (course_id, code, name) VALUES (455, '41.05', 'Geologia del Petroleo');
INSERT INTO courses (course_id, code, name) VALUES (456, '41.08', 'Petrofisica y Fluidos de Reservorios');
INSERT INTO courses (course_id, code, name) VALUES (457, '41.09', 'Ingenieria de Reservorios');
INSERT INTO courses (course_id, code, name) VALUES (458, '41.10', 'Recuperacion Asistida de Petr.');
INSERT INTO courses (course_id, code, name) VALUES (459, '41.12', 'Proyecto de Instalaciones de Superficie');
INSERT INTO courses (course_id, code, name) VALUES (460, '41.15', 'Gas y Gasolina Natural');
INSERT INTO courses (course_id, code, name) VALUES (461, '41.16', 'Analisis de Transientes de Presion');
INSERT INTO courses (course_id, code, name) VALUES (462, '41.18', 'Geofisica de Reservorios');
INSERT INTO courses (course_id, code, name) VALUES (463, '41.19', 'Desarrollo de Negocios');
INSERT INTO courses (course_id, code, name) VALUES (464, '41.21', 'Practica de Campo I');
INSERT INTO courses (course_id, code, name) VALUES (465, '41.22', 'Practica de Campo II');
INSERT INTO courses (course_id, code, name) VALUES (466, '41.24', 'Registros de Pozo');
INSERT INTO courses (course_id, code, name) VALUES (467, '41.25', 'Terminacion y Reparacion de Pozos de Petroleo y Gas');
INSERT INTO courses (course_id, code, name) VALUES (468, '41.27', 'Produccion de Petroleo');
INSERT INTO courses (course_id, code, name) VALUES (469, '41.29', 'Geoestadistica');
INSERT INTO courses (course_id, code, name) VALUES (470, '41.32', 'Geología para Ingenieros');
INSERT INTO courses (course_id, code, name) VALUES (471, '41.33', 'Materiales para la Industria Petrolera');
INSERT INTO courses (course_id, code, name) VALUES (472, '41.34', 'Desarrollo de Yacimientos');
INSERT INTO courses (course_id, code, name) VALUES (473, '41.35', 'Simulacion de Reservorios');
INSERT INTO courses (course_id, code, name) VALUES (474, '41.36', 'Operaciones Offshore - Petróleo y LNG');
INSERT INTO courses (course_id, code, name) VALUES (475, '41.37', 'Análisis Geomecánica de Cuencas Petroleras');
INSERT INTO courses (course_id, code, name) VALUES (476, '41.38', 'Evaluación de Proyectos de la Industria Petrolera');
INSERT INTO courses (course_id, code, name) VALUES (477, '41.39', 'Evaluación de Formaciones con Registros de Pozo Abierto y Entubado');
INSERT INTO courses (course_id, code, name) VALUES (478, '41.44', 'Fluidos de Perforación');
INSERT INTO courses (course_id, code, name) VALUES (479, '41.97', 'Trabajo de Investigacion Dirigido en Petroleo');
INSERT INTO courses (course_id, code, name) VALUES (480, '94.51', 'Ingles I (Bachiller)');
INSERT INTO courses (course_id, code, name) VALUES (481, '11.05', 'Calidad');
INSERT INTO courses (course_id, code, name) VALUES (482, '11.17', 'Gerenciamiento de Proyectos');
INSERT INTO courses (course_id, code, name) VALUES (483, '11.51', 'Investigacion Operativa');
INSERT INTO courses (course_id, code, name) VALUES (484, '12.08', 'Bioquimica y Microbiologia');
INSERT INTO courses (course_id, code, name) VALUES (485, '12.10', 'Introduccion a la Ingenieria Quimica');
INSERT INTO courses (course_id, code, name) VALUES (486, '12.11', 'Operaciones Unitarias I');
INSERT INTO courses (course_id, code, name) VALUES (487, '12.12', 'Operaciones Unitarias II');
INSERT INTO courses (course_id, code, name) VALUES (488, '12.13', 'Operaciones Unitarias III');
INSERT INTO courses (course_id, code, name) VALUES (489, '12.16', 'Fenomenos de Transporte');
INSERT INTO courses (course_id, code, name) VALUES (490, '12.19', 'Quimica Analitica');
INSERT INTO courses (course_id, code, name) VALUES (491, '12.20', 'Quimica-fisica');
INSERT INTO courses (course_id, code, name) VALUES (492, '12.22', 'Reactores Quimicos Avanzados');
INSERT INTO courses (course_id, code, name) VALUES (493, '12.23', 'Reactores de Polimerizacion');
INSERT INTO courses (course_id, code, name) VALUES (494, '12.24', 'Ingenieria de Reacciones y Reactores I');
INSERT INTO courses (course_id, code, name) VALUES (495, '12.25', 'Ingenieria de Reacciones y Reactores II');
INSERT INTO courses (course_id, code, name) VALUES (496, '12.26', 'Termodinamica');
INSERT INTO courses (course_id, code, name) VALUES (497, '12.27', 'Simulación de Procesos');
INSERT INTO courses (course_id, code, name) VALUES (498, '12.29', 'Modelado Matemático en Ingeniería Química');
INSERT INTO courses (course_id, code, name) VALUES (499, '12.32', 'Quimica Organica I');
INSERT INTO courses (course_id, code, name) VALUES (500, '12.33', 'Quimica Organica II');
INSERT INTO courses (course_id, code, name) VALUES (501, '12.35', 'Seminario Introducción a la Seguridad de Procesos');
INSERT INTO courses (course_id, code, name) VALUES (502, '12.36', 'Química de Macromoléculas');
INSERT INTO courses (course_id, code, name) VALUES (503, '12.51', 'Tecnologia de los Alimentos');
INSERT INTO courses (course_id, code, name) VALUES (504, '12.52', 'Bioquímica de los Alimentos');
INSERT INTO courses (course_id, code, name) VALUES (505, '12.53', 'Introducción a la Ing de los Alimentos');
INSERT INTO courses (course_id, code, name) VALUES (506, '12.54', 'Seminario: Introducción a la Tecnología de los Alimentos');
INSERT INTO courses (course_id, code, name) VALUES (507, '12.57', 'Seguridad e Inocuidad Alimentaria');
INSERT INTO courses (course_id, code, name) VALUES (508, '12.58', 'Ing. de los Alimentos');
INSERT INTO courses (course_id, code, name) VALUES (509, '12.64', 'Seminario:Ing. de Procesos Emergentes');
INSERT INTO courses (course_id, code, name) VALUES (510, '12.77', 'Industrias Quimicas');
INSERT INTO courses (course_id, code, name) VALUES (511, '12.85', 'Diseño Conceptual de Procesos');
INSERT INTO courses (course_id, code, name) VALUES (512, '12.88', 'Proyecto Final en Materiales');
INSERT INTO courses (course_id, code, name) VALUES (513, '12.90', 'Proyecto de Plantas');
INSERT INTO courses (course_id, code, name) VALUES (514, '12.95', 'Trabajo de Laboratorio de Quimica');
INSERT INTO courses (course_id, code, name) VALUES (515, '12.96', 'Trabajo Supervisado');
INSERT INTO courses (course_id, code, name) VALUES (516, '12.97', 'Trabajo de Investigacion Dirigido');
INSERT INTO courses (course_id, code, name) VALUES (517, '12.98', 'Trabajo de Investigacion Dirigido');
INSERT INTO courses (course_id, code, name) VALUES (518, '12.99', 'Trabajo Supervisado');
INSERT INTO courses (course_id, code, name) VALUES (519, '30.16', 'Metalurgia Fisica I');
INSERT INTO courses (course_id, code, name) VALUES (520, '41.28', 'Evaluacion de Proyectos en la Industria Petrolera');
INSERT INTO courses (course_id, code, name) VALUES (521, '93.53', 'Fisica II (Quimicos)');
INSERT INTO courses (course_id, code, name) VALUES (522, '93.90', 'Física Ingreso');
INSERT INTO courses (course_id, code, name) VALUES (523, '93.80', 'Matemática Ingreso');
INSERT INTO courses (course_id, code, name) VALUES (524, '12.50', 'Química Ingreso ');
INSERT INTO courses (course_id, code, name) VALUES (525, '99.05', 'Comunicación para Ing.');